### ISSUE TITLE
Possible to send own metrics?

### ISSUE THREAD

**Issue by nilskuhn** [elastic/apm-agent-js-base#169]
Hi there,
I would like to send some own, custom RUM metrics to APM server. The [API docs](https://www.elastic.co/guide/en/apm/agent/js-base/current/custom-transactions.html) shows a way to measure own spans within a transaction and report them to APM server. But I don't see a way to simply post some own metrics as metricName/Value pairs to the server.

**Comment by vigneshshanmugam** [comment]
@nilskuhn We are working on how to improve the docs in regards to setting tags on Individual spans and transactions https://github.com/elastic/apm-agent-js-base/issues/126

In the meanwhile, You can create a span using the API [startSpan](https://www.elastic.co/guide/en/apm/agent/js-base/current/api.html#apm-start-span) and report custom metrics using tags. 

```js
const span = apm.startSpan('name', 'type');
span.addTags({
   'metric1': "value",
   'metric2': "value",
});
```

If you can share what kind of metrics you are trying to capture, I would be able to help more.

**Comment by jahtalab** [comment]
Hi @nilskuhn , 
Thanks for reaching out!

We currently have a [Mark API](https://www.elastic.co/guide/en/apm/agent/js-base/current/api.html#transaction-mark) which can be used to store the current point in time with a key.

Does this work in your case?

**Comment by nilskuhn** [comment]
Hi and thanks for your responses. 

@jahtalab I don't want to use `mark` because I don't want to measure something new (relative to start of APM transaction). I want to measure my own metrics, for example visual or interactivity metrics via [perfume.js](https://zizzamia.github.io/perfume/) and just send these already measured data to APM server. 

@vigneshshanmugam Would tagging be the way to go for that. If I find the time I will give it a try.

**Comment by vigneshshanmugam** [comment]
@nilskuhn We already have support for First Contentful Paint which is captured as mark since it denotes a current point in time as part of the navigation. As @jahtalab Suggested, these metrics like First Input Delay, Time to Meaningful Paint denotes a point in time relative to the navigation event and Its better to use [Marks API](https://www.elastic.co/guide/en/apm/agent/js-base/current/api.html#transaction-mark) for that. 

If you are trying to measure something like custom user metrics using Performance.mark and Performance.measure, Then span API is a better fit

```js
const span =  apm.startSpan("render-time", "react.render");
// some heavy render task
//. You can use addTags to denote the component level timings as part of the total render time
span.addTags({
  "component-a" : "5ms",
  "component-b": "10ms"
})
span.end();
```

Hope this helps.. We also plan to support user timings https://github.com/elastic/apm-agent-js-base/issues/149
