### ISSUE TITLE
Secret token

### ISSUE THREAD

**Issue by gjelenc** [elastic/apm-agent-js-base#21]
Please add support for secret token.

**Comment by jahtalab** [comment]
Hi @gjelenc,

Thanks for reaching out.

Would you please elaborate on your use-case?
Please note that this repository is for frontend JavaScript applications therefore a secret token would be visible in the frontend code published to the users, defeating it's purpose.
Also, You might be looking for our [Node.js agent](https://github.com/elastic/apm-agent-nodejs) for backend JavaScript servers.

Cheers

**Comment by thspinto** [comment]
I was wondering about that @jahtalab. What would be the recommended approach in this case? Is leaving the APM server open to any request the only option?

**Comment by jahtalab** [comment]
Hi @thspinto ,

Unfortunately there are not many solutions to this issue mainly because of the nature of frontend application monitoring that requires us to gather metrics on the end-user's browser. 
However there are some mitigations, for example, you can use [rate_limit](https://github.com/elastic/apm-server/blob/master/apm-server.yml#L44) apm-server configuration to limit the number of requests sent to the frontend endpoint per second per IP.

We will further investigate different approaches to this issue.

**Comment by gjelenc** [comment]
Hi  @jahtalab,
My use case is to monitor [ionic](https://ionicframework.com/) application and other native android/iOS apps.
I managed to implement apm-agent-js into ionic app.
Is there any option to implement to native android and ios app ?

**Comment by jahtalab** [comment]
Thanks for your response @gjelenc ,
Unfortunately we currently don't have an agent for native android and ios apps.

If you've got a minute please fill out our [survey](https://goo.gl/forms/nLCXGCvziqalzjlP2) to help us decide on future integrations.
