### ISSUE TITLE
Add support for Metrics / Stats API

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-js-base#33]
Work is underway to add support for Metrics to the API/server: https://github.com/elastic/apm-server/issues/964
Support needs to be added to this agent too.

The default minimum set of metrics should be supported. TBD which additional metrics will be supported for this agent.

- [ ] Investigate the scope and specific metrics to add

**Comment by vigneshshanmugam** [comment]
There are couple of useful metrics in the Browser like Network Information, Memory Information. 

If we consider, Browser Memory which is available in chrome - https://webplatform.github.io/docs/apis/timing/properties/memory/, 
```js
{
  totalJSHeapSize: 12300000,
  usedJSHeapSize: 12300000,
  jsHeapSizeLimit: 1230000000
}
```
We could ideally store them as guage in the server. But the problem is unlike Server side agents(Node.js) which captures the metrics on server, browser memory metrics does not correlate to a proper environment and would vary in multitude of ways since it depends on browsing environment. 

We could have them as context information in the transaction which would make more sense than having them as metrics. 

For now, I really cannot think of any metric that we could provide as part of the Metrics Ingestion. 

Any thoughts? @alvarolobato @jahtalab ?

**Comment by jahtalab** [comment]
We've decided to postpone this for now.

**Comment by jahtalab** [comment]
Kibana issue to disable these CPU and memory usage charts: https://github.com/elastic/kibana/issues/34781
