### ISSUE TITLE
Add full http request URL to the span context

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-js-base#5]
In order to keep the span name short we remove the query string part of the http request url, however we also need to store the full url in the span context.

- [ ] [Add the required span context spec to apm-server](https://github.com/elastic/apm-server/issues/777)
- [ ] [[APM] Show http url in the Span details](https://github.com/elastic/kibana/issues/20145)

If there are no changes to the specifications, this will imply no changes to the agent

**Comment by simitt** [comment]
@jahtalab as there were changes to the API, as requested in the [APM Server Issue](https://github.com/elastic/apm-server/issues/777), I think you also need to update the agent and the task for the UI.

**Comment by jahtalab** [comment]
@simitt ! The agent is already updated! with that structure (however the integration repo may need to use the latest version).


The UI task is in the issue description above, is that what you meant?

**Comment by simitt** [comment]
Great to hear the agent is updated (I assumed it is not as this task is open and the integration testing is failing). Could you please update the integration tests to use the correct version, as otherwise it cannot be used for any UI development. 

Has there been a released agent version sending the data in the `old` format `context.http.url.raw`? If so this would be a breaking change and we should discuss if we want to release it this way.

**Comment by jahtalab** [comment]
@simitt , I've updated opbeans-frontend via [this](https://github.com/elastic/opbeans-frontend/pull/2) the integration test repo should use the new version now.

Re. The breaking change, How would you suggest to release this? As far as I can see we can only release this in 6.4 and since the change is already released in the agent (with proper semantic versioning) I don't see any other way to release it.

**Comment by simitt** [comment]
Ah yes you release the agent as `1.0` then right? So there is no issue in having a breaking change. 
Thanks for the integration test update!
